# https://rust-lang.github.io/rustfmt
tab_spaces = 3
array_width = 120
max_width = 120
binop_separator = "Front"
brace_style = "SameLineWhere"
chain_width = 120
control_brace_style = "ClosingNextLine"
fn_params_layout = "Tall"
fn_call_width = 120
fn_single_line = true
#ignore = ["/"]
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Visual"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = true
remove_nested_parens = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
#report_todo = "Always"
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Compressed"
unstable_features = false
use_field_init_shorthand = true
use_small_heuristics = "Off"
where_single_line = true
